[package]
cairo-version = "2.8.4"
name = "fragment_collector"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
default_account = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fe4c32e36c7a9d5c0a1c"
default_private_key = "0x1800000000300000180000000000030000000000003006001800006600"
